name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install

      - name: Start Backend
        run: |
          cd backend
          npm run dev &

      - name: Start Frontend
        run: |
          cd frontend
          npm run dev &
        
      - name: Cypress run component testing
        uses: cypress-io/github-action@v6
        with:
          component: true
          record: true
          working-directory: frontend
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # continue-on-error: true

      # - name: Cypress run e2e testing
      #   uses: cypress-io/github-action@v6
      #   with:
      #     record: true
      #     browser: edge
      #     working-directory: frontend
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

